Validate if peer ID is empty
libp2p/go-libp2p-peer pull request #34
Opened 2018-08-15 03:19 UTC by kishansagathiya

Fixes https://github.com/libp2p/go-libp2p/issues/370

Let me know if tests for this change are desirable.

2018-08-15 17:41 UTC, Stebalien requested changes
Thanks!  A couple of small nits and this should be good to go.

Eventually, we'll also want to validate that the peer ID is a valid multihash but I don't think we can do that efficiently at the moment (so we'll have to do it later).

2018-08-15 17:41 UTC, Stebalien commented on peer.go
> +		return errors.New("Empty peer ID")
This should probably:

1. Be a global `ErrEmptyPeerID`.
2. Be "empty peer ID" (lower case, see: https://github.com/golang/go/wiki/CodeReviewComments#error-strings)

2018-08-15 17:41 UTC, Stebalien commented
This should also have a simple test case.

2018-08-16 07:37 UTC, kishansagathiya commented on peer.go
> +
did you ask for something like
```
const ErrEmptyPeerID = "empty peer ID"
```
This is inspired from https://medium.com/@sebdah/go-best-practices-error-handling-2d15e1f0c5ee

2018-08-16 07:37 UTC, kishansagathiya commented on peer_test.go
> +
I Have used t.Error() for function that is being tested here. For failure of any other functions t.Fatal() has been used. Kinda inspired from other tests here,

2018-08-16 12:25 UTC, kishansagathiya commented on peer.go
> +
Just saw this https://github.com/libp2p/go-libp2p-swarm/blob/a00fa8aa37a812f404bfa9b9d3dccc82a66029cf/swarm_dial.go#L30-L44
Let me add changes

2018-08-16 16:36 UTC, Stebalien approved these changes

2018-08-16 16:36 UTC, merged